### ISSUE TITLE
怎么修改样式文件不能热更新

### ISSUE THREAD

**Issue by 617450941** [iview/iview-project#25]
怎么修改样式文件不能热更新

**Comment by xiamu14** [comment]
# 修改样式不能热更新
描述：修改 .vue 文件中的样式，webpack 有重新打包，但是浏览器有热更新执行，但没有将新修改的样式添加进去，而是需要刷新浏览器才能应用修改样式。
系统： window 10
浏览器： chrome
动态样式语言： less

**Comment by ctsin** [comment]
一样的问题，有解吗？

**Comment by chinieer** [comment]
一样的问题，请开发人员提供下方法
