### ISSUE TITLE
iview Date-picker设置clearable 和readonly等属性时报错

### ISSUE THREAD

**Issue by CJ-king** [iview/iview-project#26]
[Vue warn]: Invalid prop: type check failed for prop "clearable". Expected Boolean, got String.
请问这是什么原因！求大神指点

**Comment by lichbx1** [comment]
I have the same problem.

**Comment by flyingmylo** [comment]
楼上解决了吗？我也碰到这样的问题了....

**Comment by hiybm** [comment]
自己粗心了，楼上诸位在属性前加上冒号就行了
这样子： `:clearable: false`

**Comment by flyingmylo** [comment]
自己粗心了，楼上诸位在属性前加上冒号就行了
这样子：
``` :clearable: "false"```

**Comment by changfeng1800** [comment]
应该写成  :clearable= "false"
