### ISSUE TITLE
npm run build 生成的文件打开完全是空白，路由出现问题！

### ISSUE THREAD

**Issue by oxyzhg** [iview/iview-project#36]
最近在用iview做后台页面，但是在`npm run build`之后，生成的 `index_prod.html` 打开之后空白一片，css、js文件全部加载不出来，并且在改了路径之后div变成空的，什么都没有。有没有比较完美的解决方案，参考一下，或者官方修复一下。

**Comment by jia58960** [comment]
遇到了同样的问题，webpack配置文件中的publicPath不能为绝对路径'/dist/',改为相对路径'./dist/'不会出现404，但页面还是一片空白。

**Comment by toryzen** [comment]
同样遇到这个问题

**Comment by ddxmde** [comment]
https://github.com/iview/iview-project/issues/13

**Comment by miniSuper** [comment]
空白页： Cannot Get

**Comment by icarusion** [comment]
run `npm run init` first

**Comment by JasenWu** [comment]
run npm run init first 后 npm run build 入口文件生成的是index_prod.html文件对白，但打开依然是空白

**Comment by aichenxinyu** [comment]
需要配置静态服务：
npm install -g serve
serve -s build   // 默认端口5000
服务链接：http://localhost:5000  该链接会指向打包生成的index.html页面
参考create-react-app 的官方说明：https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#deployment

**Comment by ling7788** [comment]
npm run install
npm run init
npm run dev 
整个流程不报错的，却依然是 **Cannot GET /** 的同学，可以看下面内容：

iview-project 执行 npm run init 后，会在目录里生成一个 dist 和 index.html。

**如果没有这个 index.html 文件，会导致 npm run dev 和 npm run build   Cannot GET / 却不报错。**
这个情况会发生于项目部署到了git

【原因】
iview-project 的 .gitignore 默认过滤了
/index.html
于是很多项目git 部署再下载后，没有这个文件，就会一直 Cannot GET / 
【解决办法】
1 npm run init 生成 index.html 文件后
2 删除 .gitignore 的 /index.html
3 提交git
