### ISSUE TITLE
js beautify error

### ISSUE THREAD

**Issue by elviskudo** [iview/iview-project#39]
i run npm install

but i found error like this
npm ERR! path /usr/local/lib/node_modules/vue-cli/node_modules/js-beautify/js/bin/css-beautify.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/vue-cli/node_modules/js-beautify/js/bin/css-beautify.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

do you have any solution?
thanks for awesome product

**Comment by nitocode** [comment]
You have to install the version 1.6.14

More info here (it's a recent issue) : https://github.com/beautify-web/js-beautify/issues/1247#issuecomment-330144386

**Comment by elviskudo** [comment]
thanks
