### ISSUE TITLE
"npm run dev" error

### ISSUE THREAD

**Issue by linzukon** [iview/iview-project#5]
"npm run dev" error
logs:
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'vue'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           vue: ...
         }
       })
     ]
 - configuration.resolve.extensions[0] should not be empty.
    at webpack (C:\Users\58212\AppData\Roaming\npm\node_modules\webpack\lib\webpack.js:19:9)
    at processOptions (C:\Users\58212\AppData\Roaming\npm\node_modules\webpack-dev-server\bin\webpack-dev-server.js:209:13)
    at Object.<anonymous> (C:\Users\58212\AppData\Roaming\npm\node_modules\webpack-dev-server\bin\webpack-dev-server.js:228:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\dev\\nodejs\\node.exe" "C:\\Users\\58212\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=C:\\Users\\58212\\.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--registry=https://registry.npm.taobao.org" "run" "dev"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! iview-project@1.0.2 dev: `webpack-dev-server --inline --hot --compress --history-api-fallback --config webpack.dev.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iview-project@1.0.2 dev script 'webpack-dev-server --inline --hot --compress --history-api-fallback --config webpack.dev.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iview-project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --inline --hot --compress --history-api-fallback --config webpack.dev.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iview-project
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iview-project
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\58212\Desktop\workspace\iview-project\npm-debug.log

**Comment by Yooke** [comment]
same error

**Comment by jielang007** [comment]
same error

**Comment by lanten** [comment]
same error

**Comment by huguijie** [comment]
same error

**Comment by huguijie** [comment]
same error

**Comment by icarusion** [comment]
亲测没有任何问题，检查你们的安装是否正确，最好使用npm。

**Comment by lanten** [comment]
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
可能是因为新版本原因，可以说一下你用的是哪个版本吗？

**Comment by huguijie** [comment]
![image](https://cloud.githubusercontent.com/assets/22492042/22675076/7344d0d8-ed1e-11e6-82e0-27e4d5f6c863.png)

**Comment by jielang007** [comment]
![image](https://cloud.githubusercontent.com/assets/19322042/22675102/9b96d324-ed1e-11e6-87fe-65da0dc597c5.png)

**Comment by icarusion** [comment]
更新一下再试试吧，加了个webpack-dev-server，但应该不是这个原因，最好不要使用cnpm，没有在cnpm上测试过，建议连VPN使用npm安装

**Comment by linzukon** [comment]
npm也是这样的错误
