### ISSUE TITLE
样式不能热更新

### ISSUE THREAD

**Issue by wushufen** [iview/iview-project#53]
如题。
有看到其它 已关闭的 issue ，却没给出解决方案 https://github.com/iview/iview-project/issues/25
用 iView Cli 生成的项目也是这样子

还不如用 vue cli

**Comment by wushufen** [comment]
用 cli 本来就是想 开箱即用，结果难用死

**Comment by wushufen** [comment]
build 生成的 index_pod.html 没有放在 dist 里，打包起来不方便，部署还要改名字，真不知道怎么想的

**Comment by kimoziiiii** [comment]
vue-loader options 里面的loaders改成下面的就可以了 
```
{
                test: /\.vue$/,
                use: [
                    {
                        loader: 'vue-loader',
                        options: {
                            loaders: {
                                css: 'vue-style-loader!css-loader',
                                less: 'vue-style-loader!css-loader!less-loader'
                            },
                            postLoaders: {
                                html: 'babel-loader'
                            }
                        }
                    },
                    {
                        loader: 'iview-loader',
                        options: {
                            prefix: false
                        }
                    },
                ]
            }
```

**Comment by janamam** [comment]
> vue-loader options 里面的loaders改成下面的就可以了
> 
> ```
> {
>                 test: /\.vue$/,
>                 use: [
>                     {
>                         loader: 'vue-loader',
>                         options: {
>                             loaders: {
>                                 css: 'vue-style-loader!css-loader',
>                                 less: 'vue-style-loader!css-loader!less-loader'
>                             },
>                             postLoaders: {
>                                 html: 'babel-loader'
>                             }
>                         }
>                     },
>                     {
>                         loader: 'iview-loader',
>                         options: {
>                             prefix: false
>                         }
>                     },
>                 ]
>             }
> ```

缺了个!autoprefixer-loader

**Comment by cmh2016** [comment]
可以关闭bug了。
我找到原因了，它启用了一个extract-text-webpack-plugin插件，用于抽离css，减少style。样式热加载对此插件合并后的css文件无效。这个插件一般用于build时优化项目。具体详见https://github.com/webpack-contrib/extract-text-webpack-plugin。
解决方法：在webpack.dev.config.js文件中禁止使用此插件。已亲测，下面是详细配置：
  new ExtractTextPlugin({
            filename: '[name].css',
            allChunks: true,
            disable:true //开发环境下禁止抽离css文件，否则无法使用热更新
        }),

**Comment by wushufen** [comment]
已弃坑，自己写
