### ISSUE TITLE
build 失败

### ISSUE THREAD

**Issue by ilovedesert001** [iview/iview-project#7]
`
ERROR in   Error: Child compilation failed:

    1 | 
  > 2 | <!DOCTYPE htm  l>
      | ^
    3 | <html lang="zh-CN"  m>
    4 | <head>
    5 |     <title>Webpack   3mApp</title>
  :

    1 | 
  > 2 | <!DOCTYPE htm  l>
      | ^
    3 | <html lang="zh-CN"  m>
    4 | <head>
    5 |     <title>Webpack   3mApp</title>
  
  - compiler.js:76 
    [iview]/[html-webpack-plugin]/lib/compiler.js:76:16
  
  - Compiler.js:214 Compiler.<anonymous>
    [iview]/[webpack]/lib/Compiler.js:214:10

`

**Comment by ilovedesert001** [comment]
ERROR in   Error: Child compilation failed:

    1 | 
  > 2 | <!DOCTYPE htm  l>
      | ^
    3 | <html lang="zh-CN"  m>
    4 | <head>
    5 |     <title>Webpack   3mApp</title>
  :

    1 | 
  > 2 | <!DOCTYPE htm  l>
      | ^
    3 | <html lang="zh-CN"  m>
    4 | <head>
    5 |     <title>Webpack   3mApp</title>
  
  - compiler.js:76 
    [iview]/[html-webpack-plugin]/lib/compiler.js:76:16
  
  - Compiler.js:214 Compiler.<anonymous>
    [iview]/[webpack]/lib/Compiler.js:214:10

**Comment by maoycn** [comment]
Html Webpack Plugin:
  Error: Child compilation failed:
  Module build failed: SyntaxError: Unexpected token (1:0)
  > 1 |       | ^
    2 | 
    3 | 
    4 |

**Comment by maoycn** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'init' ]
2 info using npm@4.2.0
3 info using node@v7.8.0
4 verbose run-script [ 'preinit', 'init', 'postinit' ]
5 info lifecycle iview-project@2.0.0~preinit: iview-project@2.0.0
6 silly lifecycle iview-project@2.0.0~preinit: no script for preinit, continuing
7 info lifecycle iview-project@2.0.0~init: iview-project@2.0.0
8 verbose lifecycle iview-project@2.0.0~init: unsafe-perm in lifecycle true
9 verbose lifecycle iview-project@2.0.0~init: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/maoycn/Sites/iview/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/maoycn/.mos/bin
10 verbose lifecycle iview-project@2.0.0~init: CWD: /Users/maoycn/Sites/iview
11 silly lifecycle iview-project@2.0.0~init: Args: [ '-c', 'webpack --progress --config webpack.dev.config.js' ]
12 silly lifecycle iview-project@2.0.0~init: Returned: code: 2  signal: null
13 info lifecycle iview-project@2.0.0~init: Failed to exec init script
14 verbose stack Error: iview-project@2.0.0 init: `webpack --progress --config webpack.dev.config.js`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid iview-project@2.0.0
16 verbose cwd /Users/maoycn/Sites/iview
17 error Darwin 16.5.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "init"
19 error node v7.8.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 2
23 error iview-project@2.0.0 init: `webpack --progress --config webpack.dev.config.js`
23 error Exit status 2
24 error Failed at the iview-project@2.0.0 init script 'webpack --progress --config webpack.dev.config.js'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the iview-project package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     webpack --progress --config webpack.dev.config.js
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs iview-project
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls iview-project
24 error There is likely additional logging output above.
25 verbose exit [ 2, true ]
